### ISSUE TITLE
Программы: редактирование названия программ из desk

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-desk#100]
Сейчас поля все поля  в карточке Программы редактируемые, кроме названия Программы. Хотелось бы, чтобы название тоже можно было  редактировать из  deskа. Если можно сделать за <1 часа, то делаем.

**Comment by flancer64** [comment]
Сделал, выложил на live. Изначально название программы делалось read-only из соображений, что пользователи, которые создают программу, могут быть сильно удивлены, если какой-нибудь менеджер изменит её название.
