### ISSUE TITLE
Не отражается "+" на озвучке 

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-desk#101]
Сейчайс добавили партию с озвучкой. А деск не показывает "+" на колонке Звук. Заходим карточку - проверяем звук - все есть.

**Comment by minkinr** [comment]
Свеже добавленный звук
![image](https://github.com/flancer32/pwa-ra-desk/assets/103753072/5045997d-6169-42b0-83d1-4f7b543db78a)

**Comment by flancer64** [comment]
У нас озвучка привязана к пути кадрам с анимацией. Если нет ни одной анимации, то нет соответствующего фолдера для озвучки. Чтобы озвучка появилась, нужно подтвердить, что изображения будут находиться в таком-то фолдере - просто создать запись об изображении с кол-вом кадров, равным нулю (нажать на плюсик в кружочке справа от плейсхолдера картинки):
![image](https://github.com/flancer32/pwa-ra-desk/assets/5052385/709c1cc4-3bd0-444f-a46c-b3d7d37e863a)

После этого в таблице появится "+" напротив соотв. записи:
![image](https://github.com/flancer32/pwa-ra-desk/assets/5052385/0346a349-4d5b-4f8e-a137-4644fe6e3df2)

Мы по умолчанию принимаем, что новая анимация должна находиться в каталоге "./general/${id}", но так-то мы можем в любой каталог анимацию положить. А озвучка выкладывается в соотв. каталог. Пока нет записи в базе об анимации, программа не видит, в каком каталоге искать озвучку. Это не бага, это так работает.

**Comment by flancer64** [comment]
@minkinr , я закрыл задачу, а вы её переоткрыли. По ней что-то надо делать?

**Comment by minkinr** [comment]
Я поняла, откуда ноги растут.  Но мы сейчас чётко соблюдаем нумерацию папок по ID. Озвучка у нас отдельным процессом идет. И хотелось бы видеть + на звук, когда подгружен файл, без шаманства.  09:14, 9 ноября 2023 г., Alex Gusev ***@***.***>:
@minkinr , я закрыл задачу, а вы её переоткрыли. По ней что-то надо делать?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты

**Comment by flancer64** [comment]
Сделал поиск звукового файла на сервере относительно каталога `./general/`, если анимация к упражнению пока ещё не привязана. Выложил на live.
