### ISSUE TITLE
Test users deactivation

### ISSUE THREAD

**Issue by flancer64** [flancer32/pwa-ra-desk#64]
Нужно проверить, что у менеджера есть возможность деактивировать любого пользователя, после чего пользователю приложение перестаёт быть доступным (проверка сессии).

**Comment by flancer64** [comment]
Проверил, деактивация пациента и доктора работает, если приложение закрывается и открывается заново. Если просто деактивировать клиента, то текущая сессия остаётся активной. @minkinr , если нужно, чтобы клиенту шло сообщение о необходимости автоматически закрыть текущую сессию, то это нужно дорабатывать (час-полтора, навскидку).

**Comment by minkinr** [comment]
спасибо. пока доработка не нужна.

чт, 16 февр. 2023 г., 17:55 Alex Gusev ***@***.***>:
