### ISSUE TITLE
Desk: удаление кривых упражнений

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-desk#66]
Чтобы это мог делать менеджер, нужно добавлять функционал в админку - форму, предупреждения, запрос на сервер и ответ сервера. Часа на 2-3 работы. Через базу это быстро, если знать структуру таблиц или SQL-запрос (с запросом может любой справится, кто SQL знает).

**Comment by flancer64** [comment]
Удалил 366-е упражнение. Вот запрос:
```sql
delete from app_exrc where bid =366;
```
