### ISSUE TITLE
Desk стал часто глючить при загрузке 

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-desk#67]

**Comment by flancer64** [comment]
Да, я тоже заметил. Похоже, это следствие моих обновлений, которые я сделал в своей платформе. Исправлю за свой счёт.

**Comment by flancer64** [comment]
Исправил, выложил на live. Нужно ещё раз переинсталлировать приложение в браузере, после чего должно перестать глючить. То же самое и для мобильного приложения клиентов.
