### ISSUE TITLE
Возвращается старая версия desk

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-desk#70]
Странная проблема в desk. Призагрузке -грузится старая версия со старыми упражнениями. Потом делаю жёсткую перезагрузку -переходит в новую версию. при следующем заходе - опять старая.

**Comment by flancer64** [comment]
Должно помочь вот это:
![image](https://github.com/flancer32/pwa-ra-desk/assets/5052385/ecc7c4b9-25e7-4a9b-ac63-3ef4fcb45b87)

**Comment by minkinr** [comment]
Спасибо.

**Comment by flancer64** [comment]
Похоже, что жёсткая перезагрузка берёт свежую информацию снаружи, но не обновляет кэш браузера. При простой перезагрузке информация берётся из старого кэша. А если кэш почистить (и вообще, всё, что хранится на стороне браузера), то информация заходит и сохраняется уже новая.
