### ISSUE TITLE
Платежный модуль

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-desk#72]
Александр,

Думаю поменять решение по платежам. Планирую подключиться к эквайрингу и онлайн-кассе  https://yookassa.ru/

У них  есть API. Вы могли бы взглянуть? 

Подойдут ли нам их стандратные решение? Много ли дописывать. 

На нашей стороне ожидаю, что мы сможем отслеживать платежи в desk. 

Планирую 3 тарифа (базовый, продолженный, продвинутый) и промокод, которым можно обнулить.

Стоит ли нам все обсудить по телефону?

**Comment by flancer64** [comment]
Посмотрел. На первый взгляд особых проблем не видно. Если интегрироваться по схеме "Быстрый старт", то потребуется порядка 10-20 часов (навскидку). Нужно будет изменить структуры данных в базе, доработать мобильную часть, чтобы отправлять пользователя на сайт Юкассы, добавить интеграцию в мобильную/деск части приложения (смотря куда идёт подтверждение об оплате), изменить деск для отслеживания новых данных. Мне нужен будет вход в кабинет Юкассы.

Да, можем обсудить по телефону (особенно тарифы). Буду доступен завтра с 9 часов по Мск.

**Comment by flancer64** [comment]
Сделал всё, кроме льготной цены. Выложился на пилота. Если реализация устраивает, то добавлю новую группу для Пациентов и прикручу льготную цену к группе.
