### ISSUE TITLE
RDB structure for promo codes

### ISSUE THREAD

**Issue by flancer64** [flancer32/pwa-ra-desk#76]
Нужна структура в БД для хранения промо-кодов на регистрацию, а также грид и форма ввода/редактирования промо-кода.

**Comment by flancer64** [comment]
@minkinr , я полагаю, что коды будут использоваться только в верхнем регистре (или только в нижнем)?

* ПРОМО
* КОД_1234
* СКИДКА

Тогда можно будет их вводить в любом регистре:
* Промо
* коД_1234
* скиДкА

Я приведу их к нужном регистру. Это облегчит общение с пользователями, когда они будут жаловаться на то, что код не сработал.

**Comment by minkinr** [comment]
да, ок.

вт, 18 июл. 2023 г., 14:19 Alex Gusev ***@***.***>:

**Comment by flancer64** [comment]
Получилось как-то так:
![image](https://github.com/flancer32/pwa-ra-desk/assets/5052385/592111f7-0958-47f3-afea-a36cb2f6cede)
