### ISSUE TITLE
в desk Не могу поменять роль с Пациент на Врач

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-desk#77]
Поле Роль - серое, не позволяет выбор. 

Кеш на телефоне стирала.

**Comment by minkinr** [comment]
![Screenshot_20230805_223813_Chrome.jpg](https://github.com/flancer32/pwa-ra-desk/assets/103753072/ca0a1a84-165d-4560-8adf-9f8f2bf5fc64)

**Comment by flancer64** [comment]
Это логика работы приложения. Сделано специально. Врача можно "опустить" до Пациента, а Пациента до врача "поднять" нельзя. Приложение не предусмотрено для скачков ролей туда-сюда. Я даже не думал в эту сторону. Скорее всего, работать будет (особенно, если полностью переинсталлировать приложение), но также будут и проблемы с данными.

Я могу вручную перевести пользователя во Врача либо могу снять ограничение на смену роли.

**Comment by minkinr** [comment]
Александр, я раньше именно здесь меняла Пациента на Врача. Сейчас вспомнила, что можно прислать приглашение. Буду так делать на будущее. Пока ничего не делаем, кроме как вручную перевести  ***@***.*** во врача. 09:13, 6 августа 2023 г., Alex Gusev ***@***.***>:
Это логика работы приложения. Сделано специально. Врача можно "опустить" до Пациента, а Пациента до врача "поднять" нельзя. Приложение не предусмотрено для скачков ролей туда-сюда. Я даже не думал в эту сторону. Скорее всего, работать будет (особенно, если полностью переинсталлировать приложение), но также будут и проблемы с данными.
Я могу вручную перевести пользователя во Врача либо могу снять ограничение на смену роли.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты

**Comment by flancer64** [comment]
Сделал пользователя №493 (s.minkina26@yandex.ru) Врачом. Да, у нас планировалось, что Врачом становятся по приглашению. С публичной формы регистрации можно стать только Пациентом.

**Comment by flancer64** [comment]
> Александр, я раньше именно здесь меняла Пациента на Врача.

Возможно, так было до момента появления Клиник. Сейчас каждый Врач привязан к клинике, поэтому сначала вводится клиника, а потом отправляется приглашение, в котором выбирается клиника. Сейчас Врач  №493 не привязан к какой-либо клинике.

**Comment by flancer64** [comment]
@minkinr , к какой клинике привязать врача №493?

**Comment by minkinr** [comment]
![Screenshot_20230805_223813_Chrome.jpg](https://github.com/flancer32/pwa-ra-desk/assets/103753072/ca0a1a84-165d-4560-8adf-9f8f2bf5fc64)

Это моя дочь, она тестер. Может сделаем отдельную клинику, типа  Rehapp?

**Comment by flancer64** [comment]
У меня она как Доктор:
![image](https://github.com/flancer32/pwa-ra-desk/assets/5052385/293aae96-267e-47f4-8d99-0ab6338efff3)

**Comment by flancer64** [comment]
Сейчас у нас три клиники, могу на любую из них прикрутить пользователя:
![image](https://github.com/flancer32/pwa-ra-desk/assets/5052385/9ad0a10e-5598-4725-8553-d34f2b97ffc1)

Имя клиники можно изменить.

**Comment by minkinr** [comment]
#66 Rehapp14:49, 7 августа 2023 г., Alex Gusev ***@***.***>:
Сейчас у нас три клиники, могу на любую из них прикрутить пользователя:

Имя клиники можно изменить.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты

**Comment by flancer64** [comment]
Связал пользователя №493 и клинику №66.

**Comment by minkinr** [comment]
Александр,

тот же случай, надо перевести Пациента в статус Doctor: #443: Евгений

**Comment by flancer64** [comment]
Изменил пользователю №443 роль в приложении с Patient на Doctor и связал его с клиникой №66.

**Comment by flancer64** [comment]
У пользователя 443 была связь "Пациент - Доктор" с пользователем 2. Разорвал.
