### ISSUE TITLE
Desk: карточка Упражнения - источник, Примечание, Eng.title

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-desk#78]
Александр, добрый день, 

мы сейчас  пополняем базу и поняли, что нам нужно скорректировать поля в карточке Упражнения: 

1) Источник -  это может быть ссылка на:
- клинику/врача из нашей базы  
- видео на ютубе 
- файл на яндекс.диске. 
Наверно, надо просто текстовое поле. 

2) English title - текст в свободной форме

3) Текущее поле Примечание - текст в свободной форме - оставляем 

4) Текущее поле Группа не нужно. Можно пока залочить потом уберём.

**Comment by flancer64** [comment]
Добавил English Title:
![image](https://github.com/flancer32/pwa-ra-desk/assets/5052385/3e73cb7a-db03-4096-9d30-185df0fedcaa)

**Comment by flancer64** [comment]
Скрыл инициализационную группу, отвязал примечания от группы, вывел примечания и источник на форму:
![image](https://github.com/flancer32/pwa-ra-desk/assets/5052385/12767602-b363-436f-9b62-d3a98534523b)

**Comment by minkinr** [comment]
@flancer64 , все хорошо. выкатываем на Live.

**Comment by flancer64** [comment]
Выложился вместе с #79
