### ISSUE TITLE
Desk: отчёт по упражнениям

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-desk#79]
Для контроля базы упражнений, хотелось бы отчёт: 
- по горизонтали -   все поля карточки упражнения, вкл. номер и путь
- по вертикали - сами упражнения

**Comment by flancer64** [comment]
Вы хотите отчёт в каком виде - печатном (pdf) или табличном (csv)? Или просто переделать грид упражнений из "плиточной" формы в табличную?

**Comment by minkinr** [comment]
плиточную форму пока не трогаем, делаем второй  вид -  табличный. это  ок?

пн, 28 авг. 2023 г., 12:50 Alex Gusev ***@***.***>:

**Comment by flancer64** [comment]
Получается как-то так:

![image](https://github.com/flancer32/pwa-ra-desk/assets/5052385/83b4bcd0-9bdc-46b2-bb4f-59d553b972df)

Я добавил переключатель вида грида: Плитка/Таблица.

**Comment by flancer64** [comment]
Вот этот переключатель:
![image](https://github.com/flancer32/pwa-ra-desk/assets/5052385/ff805d2e-9cd6-4271-bd71-82a635a8ecd1)

**Comment by flancer64** [comment]
@minkinr , выложился на пилота, можно смотреть и делать замечания по реализации: https://desk.ra.pilot.teqfw.com/

**Comment by minkinr** [comment]
@flancer64 , да, примерно то, что нужно.
Надо добавить  остальные поля (отмечены розовым на картинке):
![Снимок экрана 2023-08-29 210012](https://github.com/flancer32/pwa-ra-desk/assets/103753072/078508c3-7bd0-4102-9f16-a935db60d792)
 
Также было бы очень полезно, но не знаю как сложно добавить:
1) мини-фотка
2) тэги (скопом или отдельными полями)
3) звук:  да/ нет (есть звуковой файл или нет)

Как я поняла Поле Примечание в карточке в таблице выглядит как Заметка (надо сделать Примечание).

**Comment by flancer64** [comment]
> Что такое Публ (+) в таблице?

Это флаг публичности упражнения. В https://github.com/flancer32/pwa-ra-mob/issues/190 была заложена структура, чтобы можно было сделать упражнение непубличным, а доступным только определённому доктору.

**Comment by flancer64** [comment]
По анимациям. У нас структурно заложена возможность иметь более одной анимации на упражнение. В отчёте я выдаю данные только по первому упражнению.

**Comment by minkinr** [comment]
да14:34, 30 августа 2023 г., Alex Gusev ***@***.***>:
По анимациям. У нас структурно заложена возможность иметь более одной анимации на упражнение. В отчёте я выдаю данные только по первому упражнению.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты
