### ISSUE TITLE
Desk: фильтры

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-desk#80]
Перестали работать фильтры в разделе Упражения в deske  и в форме Плитки и форме Таблица
![Снимок экрана 2023-09-03 124247](https://github.com/flancer32/pwa-ra-desk/assets/103753072/4cfdbbb8-6a51-446b-9f3f-970a13c969c1)

**Comment by flancer64** [comment]
Внёс исправления. Выложил на live & pilot.
