### ISSUE TITLE
Статус упражнения активное/неактивное.

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-desk#82]
@flancer64 , вы могли бы прикинуть кол-во часов доработки для добавления в карточку упражнения статуса активное/неактивное. Активные доступны пользователям. Неактивные только на сервере и не грузятся пользователям. 

Примеры неактивных упражнений:
- новые  упражнения, которые не до конца оформлены, типа имеют карточку с рписанием, но без видео
- кривые/задвоенные

**Comment by flancer64** [comment]
Часа три, навскидку. У нас есть поле public - может быть его можно использовать. Тогда часа потора-два.

**Comment by minkinr** [comment]
Делаем. Мне кажется public мы для чего-то такого и планировали. Можем так
назвать Public/Non-public.

вт, 5 сент. 2023 г., 16:51 Alex Gusev ***@***.***>:

**Comment by minkinr** [comment]
надо, чтобы это поле было видно в табличной форме

**Comment by flancer64** [comment]
Использовал поле public, добавил его на форму и прокинул до операции сохранения на сервере. Мобильную часть приложения не трогал, там поле public и так учитывалось. Выложился на пилота и боевой - можно смотреть.

**Comment by minkinr** [comment]
@flancer64 , добрый день, я правильно понимаю, что на mob непубличные не должны показываться? 

Я #695 сделала непубличным в desk, но в mob оно все ещё видно. Кеши чистила.

**Comment by flancer64** [comment]
А где видно? В списке упражнений, доступных для включения в программу не должно быть видно. Просто у нас есть ещё №538, которое также называется.

![image](https://github.com/flancer32/pwa-ra-desk/assets/5052385/df04effe-e574-4caf-bb03-01864fd61b55)

**Comment by flancer64** [comment]
Посмотрите, сколько упражнений доступно в Конструкторе, сделайте ещё одно из упражнений непубличным и обновите список упражнений в Конструкторе. Должно стать на одно меньше.

**Comment by minkinr** [comment]
https://github.com/flancer32/pwa-ra-desk/assets/103753072/2aeaf024-6390-480c-ba1f-6fdd4f796b87

**Comment by flancer64** [comment]
У меня другая картинка - 184 упражнения против 189 у вас:
![image](https://github.com/flancer32/pwa-ra-desk/assets/5052385/2896da1d-297b-4316-a3e8-f5280ce36ece)

Вы точно на боевом смотрите мобильную часть? Возможно, пилот. И ещё такой момент, что доктор, который является владельцем упражнения, будет его видеть в любом случае. Я вхожу под пользователем doc@gmail.com.

**Comment by minkinr** [comment]
> Посмотрите, сколько упражнений доступно в Конструкторе, сделайте ещё одно из упражнений непубличным и обновите список упражнений в Конструкторе. Должно стать на одно меньше.

В desk 189 упражнений, из них 5 непубличных. В mob 189 упр. 

Кстати, вы можете добавить  в desk счетчик непубличных упр. Напр,  Всего:189/184 [публичные/непубличные]

![Screenshot_20230906_114442_Chrome.jpg](https://github.com/flancer32/pwa-ra-desk/assets/103753072/5b456db4-adb2-40d8-90de-003c51f66170)

**Comment by minkinr** [comment]
![Screenshot_20230906_114857_Chrome.jpg](https://github.com/flancer32/pwa-ra-desk/assets/103753072/8dd63aa9-edef-49da-8e05-887f08fd481d)

**Comment by flancer64** [comment]
@minkinr , а какой пользователь?

**Comment by flancer64** [comment]
> Кстати, вы можете добавить в desk счетчик непубличных упр. Напр, Всего:189/184 [публичные/непубличные]

Хорошо.

**Comment by minkinr** [comment]
***@***.***

ср, 6 сент. 2023 г., 11:50 Alex Gusev ***@***.***>:

**Comment by flancer64** [comment]
Github вырезал email :(

![image](https://github.com/flancer32/pwa-ra-desk/assets/5052385/4f1483b3-1e14-467d-8284-2e727ff8df39)

**Comment by flancer64** [comment]
Всё, понял. Вы заходите, как пациент, а я - как доктор. Получается, что поле public работает только для докторов. Доктора в конструкторе видят только публичные упражнения и свои, если они не публичные. А пациент видит все. 

Да, придётся вводить новый атрибут.

**Comment by minkinr** [comment]
Поняла. Пока не делаем. Думаю.11:58, 6 сентября 2023 г., Alex Gusev ***@***.***>:
Всё, понял. Вы заходите, как пациент, а я - как доктор. Получается, что поле public работает только для докторов. Доктора в конструкторе видят только публичные упражнения и свои, если они не публичные. А пациент видит все.
Да, придётся вводить новый атрибут.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты

**Comment by minkinr** [comment]
да12:13, 6 сентября 2023 г., Alex Gusev ***@***.***>:

Кстати, вы можете добавить в desk счетчик непубличных упр. Напр, Всего:189/184 [публичные/непубличные]

это делаем?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты

**Comment by minkinr** [comment]
Подумала. Текущая концепция, что пациент не может заниматься самоназначением упражнений, поэтому наверно легче заблокировать пациентам "+". 

Мысли вслух. 
Вообще, эта тема может ли пациент назначать себе упражнения или нет, не решена однозначно. Много голосов за и против. 

Один из вариантов, который примеряет оба подхода, это сделать два тарифа: 
Тариф 1 - без возможности самоназначений 
Тариф 2 - с возможностью самоназначений и полным конструктором и предупреждением, что ответственность пациент берет на себя сам.  

Насколько сложно реализуется такой двухтарифный подход?

**Comment by flancer64** [comment]
> Насколько сложно реализуется такой двухтарифный подход?

Не думаю, что сильно сложно. У нас уже есть более одной роли для пациента (простой и промо) и отдельный тариф для промо-группы в настройках. Нужно будет ограничить доступ к функционалу и выборку тарифа, а также логику перехода между ролями подправить. Правда это уже будет трёхтарифный подход. Навскидку - 4-6 часов.

**Comment by minkinr** [comment]
Это хорошая новость. Пока трех тарифный подход не делаем, а "+" для пациентов блокируем.

**Comment by flancer64** [comment]
Добавил кол-во непубличных упражнений в заголовок:

![Image](https://github.com/flancer32/pwa-ra-desk/assets/5052385/b3a51973-94cb-4068-9fd5-f8dc6f621cdd)

**Comment by minkinr** [comment]
Ой, нужны были Публичные. Я наверно ошиблась в задании

чт, 7 сент. 2023 г., 15:42 Alex Gusev ***@***.***>:

**Comment by flancer64** [comment]
Исправил:

![Image](https://github.com/flancer32/pwa-ra-desk/assets/5052385/5bedda05-c843-4d9f-9a4a-66b1a74939c5)
