### ISSUE TITLE
 Доступ для Стаси к серверу

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-desk#86]
@flancer64 , 

Моя дочь Станислава будет администратором базы упражнений. 

Она должна иметь возможность загружать упражнения jpg и озвучку. 

Мы планируем поставить ей консоль WinSCP, через который она будет делать эти манипуляции. 

Ей нужено настроить доступ до сервера. Помогите, пожалуйста.

**Comment by flancer64** [comment]
Создал пользователя на сервере. Параметры доступа выслал.
