### ISSUE TITLE
Desk: Карточка упражнения: Предзаполненность

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-desk#89]
Новая карточка должна быть предзаполнена: 
1) путь: general/[ID]
2) размеры: 1080 и 1080
3) jpg
4) кадров: 1
5) снять галку с Public
6) разрешить пустое поле в Описании

Можно ли  автоматом или полу-автоматом считывать кол-во кадров, когда анимация подгружена? У нас сильно тормозится процесс на этом этапе. Можем обсудить альтернативы голосом. 

Статусы: 
1. Проект карточки: вкл озвучку, описание, тэги
2. Съёмка проведена
3. Обработано,  вкл загрузку, zip и кол-во кадров
4. QC done -> Public

**Comment by flancer64** [comment]
> Можно ли автоматом или полу-автоматом считывать кол-во кадров, когда анимация подгружена? У нас сильно тормозится процесс на этом этапе. Можем обсудить альтернативы голосом.

Да, можно. Кол-во кадров равно кол-ву файлов в каталоге. Я могу вычислять это значение при сохранении карточки упражнения.

**Comment by flancer64** [comment]
Я вынесу подсчёт кадров и статусы упражнения в отдельные задачи, чтобы не смешивать код в коммитах.

**Comment by minkinr** [comment]
Александр, имейте ввиду, что у нас процесс такой:Сначала создаётся и сохраняется проект карточки. В этот момент папка с  jpg  отсутствует . Предлагаю если папки нет , то писать 1 кадр и 0 кадров. 11:45, 5 октября 2023 г., Alex Gusev ***@***.***>:

Можно ли автоматом или полу-автоматом считывать кол-во кадров, когда анимация подгружена? У нас сильно тормозится процесс на этом этапе. Можем обсудить альтернативы голосом.

Да, можно. Кол-во кадров равно кол-ву файлов в каталоге. Я могу вычислять это значение при сохранении карточки упражнения.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты

**Comment by flancer64** [comment]
Я думаю, что нужно дать возможность сохранять базовое упражнение без анимации, но не давать возможность его публиковать.

**Comment by minkinr** [comment]
да. публиковать только с видео, озвучкой, назв, рус. описание. тегами.14:11, 5 октября 2023 г., Alex Gusev ***@***.***>:
Я думаю, что нужно дать возможность сохранять базовое упражнение без анимации, но не давать возможность его публиковать.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты

**Comment by flancer64** [comment]
> путь: general/[ID]

Проблема в том, что ID появляется только после сохранения упражнения. Судя по тому, что анимация появляется после регистрации упражнения, на момент добавления анимации ID уже должен быть известен. Посмотрим, что получится.

**Comment by minkinr** [comment]
В принципе ок, если ID будет создаваться во время сохранения карточки14:40, 5 октября 2023 г., Alex Gusev ***@***.***>:

путь: general/[ID]

Проблема в том, что ID появляется только после сохранения упражнения. Судя по тому, что анимация появляется после регистрации упражнения, на момент добавления анимации ID уже должен быть известен. Посмотрим, что получится.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты

**Comment by flancer64** [comment]
> разрешить пустое поле в Описании

У нас запрет на пустое поле на уровне базы данных (`app_exrc.desc`). Проще сделать, чтобы в форму добавлялось какое-то значение по-умолчанию. Например, "n/a" (not available):

![image](https://github.com/flancer32/pwa-ra-desk/assets/5052385/2664f7fa-ee18-4ab2-8e86-ddf21c3eea29)

При создании карточки базового упражнения медиа-данные (анимация и озвучка) для ввода недоступны. Данные можно вводить только после сохранения карточки (когда появляется идентификатор базового упражнения).

**Comment by flancer64** [comment]
Конечный вариант выглядит так:
![image](https://github.com/flancer32/pwa-ra-desk/assets/5052385/6d958931-79bb-4403-988e-27b69b3c3e40)

Я перенёс код, относящийся к медиа (анимация и озвучка), в отдельный компонент. Также доработал компонент по отображению анимации, чтобы он не пытался искать картинку, если кадры равны 0.

**Comment by flancer64** [comment]
Кнопка "Добавить анимацию" доступна только для сохранённых упражнений:
![image](https://github.com/flancer32/pwa-ra-desk/assets/5052385/e2d35ef3-e492-48bf-9a8f-47a61ce6ffd5)

**Comment by flancer64** [comment]
Т.е., на начальных шагах, пока анимация не подгружена, карточка упражнения вполне себе может существовать без данных о медиа:
![image](https://github.com/flancer32/pwa-ra-desk/assets/5052385/e6027d7a-d1dc-4d6c-82dc-32fd07482c75)

Чтобы отсутствующее фото не подгружалось (как в 732), достаточно кол-во кадров поставить в 0.

**Comment by flancer64** [comment]
выложил на live & pilot
