### ISSUE TITLE
Statuses for base exercises

### ISSUE THREAD

**Issue by flancer64** [flancer32/pwa-ra-desk#90]
Статусы:

- Проект карточки: вкл озвучку, описание, тэги
- Съёмка проведена
- Обработано, вкл загрузку, zip и кол-во кадров
- QC done -> Public

**Comment by flancer64** [comment]
Я вижу такие состояние для карточки базового упражнения:
* PROJECT - Проект карточки: вкл озвучку, описание, тэги
* CUT - Съёмка проведена
* PROCESSED - Обработано, вкл загрузку, zip и кол-во кадров
* PUBLISHED - QC done -> Public

Начальное состояние - PROJECT
Переход в состояние CUT нужно делать вручную - могу сделать кнопку для перевода в это состояние. Вполне возможно, что это состояние лишнее - оно нужно лишь для учёта внешней деятельности (съёмки анимации) и может вестись вне админки (но может и в).
Переход в состояние PROCESSED можно делать автоматом, когда есть данные по первой анимации (кол-во кадров и время анимации). Переход в состояние PUBLISHED нужно делать по кнопке. При этом флаг Public нужно делать readonly и давать возможность переводить упражнение обатно в состояние PROCESSED.

Тут придётся добавлять новое поле в базу данных и протягивать его по всем моделям до UI'я деска (как минимум, а то и мобильного тоже).

Возникает вопрос о начальном значении этого поля. Полагаю, что для упражнений, в котором кол-во кадров больше 0 и public=true ставить значение PUBLISHED, если значение public=false - ставить значение PROCESSED, если кол-во кадров равно 0, то ставить значение PROJECT.

**Comment by minkinr** [comment]
1. Возврат в project - Столкнулись с ситуацией, что на этапе обработки или quality control понимаем, что упражнение надо отправить на пересъемку, т.е. вернуть карточку назад в статус Project
2. Добавить доп. статус - Reserve (часть карточек отменяется (например, поняли, что упражнение уже есть в базе) и попадает в резерв)

**Comment by flancer64** [comment]
Вот такие переходы:
![image](https://github.com/flancer32/pwa-ra-desk/assets/5052385/05666808-83ee-4470-b358-c8e765a60e8a)

**Comment by flancer64** [comment]
выложился на live

**Comment by minkinr** [comment]
@flancer64 , 

Думаю, надо поправить. Из любого уровня должно быть можно вернуться в project. 

То есть: 
Из project в cut или reserve
Из cut в processed или project
Из processed в published или project
Из published в project
Из reserve в project

**Comment by flancer64** [comment]
Добавил кнопку "В проект"
![image](https://github.com/flancer32/pwa-ra-desk/assets/5052385/595103ef-9297-4cb1-b5dd-5943083ab44e)

Стало так:
![image](https://github.com/flancer32/pwa-ra-desk/assets/5052385/c7d3cb0f-73e6-41a1-a0e2-334df11f1fd8)

**Comment by flancer64** [comment]
Выложил на live.

**Comment by minkinr** [comment]
@flancer64 

в Резерв и обратно должен попадать из Project, а не processed.

**Comment by flancer64** [comment]
Тогда вот такая диаграмма получается:
![image](https://github.com/flancer32/pwa-ra-desk/assets/5052385/1fadffb9-0d8e-4dc6-be16-ff33d649beb4)

**Comment by flancer64** [comment]
Выложил изменения на live.
