### ISSUE TITLE
New base exercise card is failed on editing the description

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-desk#98]
при внесении карточки упражнения в поле Описание, карточка ломается ![Screenshot_20231030_150629_Chrome.jpg](https://github.com/flancer32/pwa-ra-desk/assets/103753072/a415e93c-3c0c-4ada-9e8c-7683e4530cfc)

**Comment by flancer64** [comment]
Пофиксил и выложил на live.
