### ISSUE TITLE
Новые карточки упражений создаются со статусом PROCESSED

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-desk#99]
Новые  карточки упражений создаются со статусом PROCESSED, а не Project

???

**Comment by flancer64** [comment]
Не должны бы. Посмотрю завтра.

**Comment by flancer64** [comment]
Нашёл ошибку в коде. Не сбрасывался статус в форме добавления/редактирования упражнения. Если открыть какую-то существующую карточку, где у упражнения статус PROCESSED, а потом создать новое упражнение, то статуст остаётся от предыдущего упражнения. Исправил.
